theme: jekyll-theme-architect
title: Introduction to Bioinformatics Class (Spring 2018)
description: Here to learn the basics of bioinformatics!
logo: https://bioboot.github.io/bimm143_S18/assets/img/logo.png
