---
title: "Lecture 16"
author: "Cassandra Chow"
date: "May 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading several packages
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(readr)
```

Importing data from the TnSeq experiment
```{r}
exp_data <- read.csv("Experimental_results.csv")
head(exp_data)
```

We will be ignoring X in our data
```{r}
#using the select function either keeps the variable, or ask to remove it
exp_data <- select(exp_data, -X)
head(exp_data)
```

Preparing to plot
```{r}
#We will need to modify the plot so we can put time/frequency in
exp_rearranged <- gather(exp_data, Generation, Frequency, H_0:H_96)
head(exp_rearranged)
```

```{r}
#We want to remove H(hours) in our data frame, so we separated H into another column and removed it
table_for_graph <- separate(exp_rearranged, Generation, into = c("H","Time"))
table_for_graph <- select(table_for_graph, -H)
head(table_for_graph)
```

```{r}
#Lastly, we want to omit any NA data from our set, and make sure that time is numeric
table_cleaned <- na.omit(table_for_graph)
table_cleaned$Time <- as.numeric(table_cleaned$Time)
head(table_cleaned)
```

We have multiple strains, so we want to separate them
```{r}
DivAnc<-filter(table_cleaned, table_cleaned$Strain=="DivAnc")
L013<-filter(table_cleaned, table_cleaned$Strain=="L013")
```

Plotting time!
```{r}
DivAnc_plot=ggplot(DivAnc)+geom_line(aes(x=Time,y=Frequency,group=BC_ID),alpha=.2,colour="#000033")+ggtitle("DivAnc_SC3")+theme(plot.title = element_text(hjust = 0.5))+xlab("Time, hours") + ylab("Log10(Barcode frequency)")
DivAnc_plot
```

```{r}
L013_plot=ggplot(L013)+geom_line(aes(x=Time,y=Frequency,group=BC_ID),alpha=.2,colour="#CC6633")+ggtitle("L013_SC3")+theme(plot.title = element_text(hjust = 0.5))+xlab("Time, hours") + ylab("Log10(Barcode frequency)")
L013_plot
```

```{r}
#Projecting two different graphs
ggplot(table_cleaned)+geom_line(aes(x=Time,y=Frequency,group=BC_ID),alpha=.2,colour="#000033")+facet_grid(.~Strain)+ggtitle("Barcode trajectories")+theme(plot.title = element_text(hjust = 0.5))+xlab("Time, hours") + ylab("Log10(Barcode frequency)")
```

We should look at one mutation
```{r}
#We'll look at 34
mut34 <- filter(table_cleaned, table_cleaned$Mut_ID == "34")
mut34
```


```{r}
ggplot(mut34,aes(Time, Frequency, group=BC_ID, color=BC_ID))+geom_line()+theme(legend.position="none")+facet_grid(.~Strain)+ggtitle("Mutation_34")+xlab("Time, hours") + ylab("Log10(Barcode frequency)")+theme(plot.title = element_text(hjust = 0.5))
```

We see that the negative log is quite insignificant, let's remove it out
```{r}
mut34_f<-filter(mut34, mut34$Frequency>(-5))
mut34_f
```

```{r}
ggplot(mut34_f,aes(Time, Frequency, group=BC_ID, color=BC_ID))+geom_line()+theme(legend.position="none")+facet_grid(.~Strain)+ggtitle("Mutation_34")+xlab("Time, hours") + ylab("Log10(Barcode frequency)")+theme(plot.title = element_text(hjust = 0.5))
```

```{r}
ggplot(mut34_f,aes(Time, Frequency, colour = BC_ID, group=BC_ID))+geom_point()+geom_smooth(se = FALSE, method = "lm")+facet_grid(.~Strain)+theme(legend.position="none")+ggtitle(paste("Mutation",34, sep="_"))+xlab("Time, hours")+ ylab("Log10(Barcode frequency)")
```

```{r}
# Lets become familiar with lm function:

# For this exercise, take the filtered data for mutation 34 (mut34_f) and filter out information about one barcode you like

# I have chosen BC_ID=25361 in DivAnc strain
BC_25361<-filter(mut34_f, mut34_f$BC_ID=="25361", mut34_f$Strain=="DivAnc")
BC_25361
```

```{r}
ggplot(BC_25361,aes(Time, Frequency, colour = BC_ID))+geom_point()+theme(legend.position="none")+ggtitle("BC_25361")+xlab("Time, hours") + ylab("Log10(Frequency)")
```

```{r}
#Lets use lm function to fit the line to these points:
ggplot(BC_25361,aes(Time, Frequency, colour = BC_ID))+geom_point()+geom_smooth(se = FALSE, method = "lm")+theme(legend.position="none")+ggtitle("BC_25361")+xlab("Time, hours") + ylab("Log10(Frequency)")
```

```{r}
# Lets check what data does lm function return:
regression_model<-lm(Frequency~Time,BC_25361)
summary_data<-summary(regression_model)
summary_data
```

```{r}
# The information we are interested in is the value of Slopeand Intercept of this line:
# Let's try to access them:

# Time
Time<-summary_data$coefficients[2]
Time

Intercept<-summary_data$coefficients[1]
Intercept
```

Find slopes for each barcode
```{r}
# Lets create the file:
data_header=matrix(data = NA,nrow = 1,ncol = 7)
        data_header[1]="Mut_ID"
        data_header[2]="BC_ID"
        data_header[3]="Strain"
        data_header[4]="Slope"
        data_header[5]="Intercept"
        data_header[6]="R^2"
write.table(data_header,"~/Documents/1st_Year/TAing/BIMM143/BIMM143_data/Tnseq_practice_output.csv",append = FALSE, sep = ",",eol="\n",dec=".",row.names = FALSE,col.names = FALSE)
```

```{r}
for (mut in unique(table_cleaned$Mut_ID)) {
    mut_data=filter(table_cleaned,table_cleaned$Mut_ID==paste(mut))
    #now we have all data for each mutation separately
    for (bc in unique (mut_data$BC_ID)) {
      #now we filtered data for each barcode within 1 mutation
      bc_mut_data=filter(mut_data,mut_data$BC_ID==paste(bc))
      for (strain in unique (bc_mut_data$Strain)) {
        str_bc_mut_data=filter(bc_mut_data,bc_mut_data$Strain==paste(strain))
        #only considering combinations with 3 or more data points - anything less is statistically insignificant
        if (nrow(str_bc_mut_data)>2){
          regression_model=lm(Frequency~Time,str_bc_mut_data)
          summary_data=summary(regression_model)
          #now write to the output file! Prepare the data array first
          data_output=matrix(data = NA,nrow = 1,ncol = 6)
          data_output[1]=mut
          data_output[2]=bc
          data_output[3]=strain
          #slope
          data_output[4]=summary_data$coefficients[2]
          #intercept
          data_output[5]=summary_data$coefficients[1]
          #r-squared
          data_output[6]=summary_data$r.squared
          #time to write
          write.table(data_output,"~/Documents/1st_Year/TAing/BIMM143/BIMM143_data/Tnseq_practice_output.csv",append = TRUE, sep = ",",eol="\n",dec=".",row.names = FALSE,col.names = FALSE)
      }
    }
  }
 }
```
